# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20180426_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='updated',
        ),
    ]
