# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_healthclub_healthdiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
