# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20180501_0515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthdiary',
            old_name='date',
            new_name='timestamp',
        ),
    ]
