# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menus', '0004_auto_20180501_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Healthclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerdate', models.DateTimeField(auto_now=True)),
                ('healthclub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.HealthClub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
